### ISSUE TITLE
observations without observer number

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#39]
The following three observations have no `WaarnemerNummer`:

Nummer | Datum | KleurringNummer | PlaatsGemeente | PlaatsLandCode | WaarnemerNummer
--- | --- | --- | --- | --- | ---
83331 | 2010-11-25 | KSH | Bas-en-Basset | FR | 
92295 | 2013-06-16 | KVAC | Noordwijk | NL | 
136534 | 2018-05-05 | UTAJ | Borssele | NL | 

@EricStienen : could you please check it? Thanks.

**Comment by EricStienen** [comment]
solved at DB-level

**Comment by damianooldoni** [comment]
@EricStienen : thanks. For the first and the third one solved, but I still don't see a `WaarnemerNummer` for observation with number 92295. Could you please recheck it? Thanks a lot!

**Comment by damianooldoni** [comment]
Checked again. Solved at database level. Thanks.
